myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onlinecourse.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'onlinecourse'
urlpatterns = [
    path(route='', view=views.CourseListView.as_view(), name='index'),
    path('registration/', views.registration_request, name='registration'),
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    # ex: /onlinecourse/5/
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    # ex: /enroll/5/
    path('<int:course_id>/enroll/', views.enroll, name='enroll'),

    # route for submit view
    path('<int:course_id>/submit/', views.submit, name='submit'),
    # route for show_exam_result view
    path('course/<int:course_id>/submission/<int:submission_id>/result/', views.show_exam_result,
                       name='show_exam_result'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinecourse/models.py
import sys
from django.utils.timezone import now
try:
    from django.db import models
except Exception:
    print("There was an error loading django modules. Do you have django installed?")
    sys.exit()

from django.conf import settings
import uuid


"""Course Instructor model"""
class Instructor(models.Model):
    """ Represents an instructor """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_time = models.BooleanField(default=True)
    total_learners = models.IntegerField()

    def __str__(self):
        return self.user.username


""" Learner model """
class Learner(models.Model):
    """ Represents a learner / student """    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    STUDENT = 'student'
    DEVELOPER = 'developer'
    DATA_SCIENTIST = 'data_scientist'
    DATABASE_ADMIN = 'dba'
    OCCUPATION_CHOICES = [
        (STUDENT, 'Student'),
        (DEVELOPER, 'Developer'),
        (DATA_SCIENTIST, 'Data Scientist'),
        (DATABASE_ADMIN, 'Database Admin')
    ]
    occupation = models.CharField(
        null=False,
        max_length=20,
        choices=OCCUPATION_CHOICES,
        default=STUDENT
    )
    social_link = models.URLField(max_length=200)

    def __str__(self):
        return self.user.username + "," + \
               self.occupation


""" Course model """
class Course(models.Model):
    """ Represents a course """
    name = models.CharField(null=False, max_length=30, default='online course')
    image = models.ImageField(upload_to='course_images/')
    description = models.CharField(max_length=1000)
    pub_date = models.DateField(null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Enrollment')
    total_enrollment = models.IntegerField(default=0)
    is_enrolled = False

    def __str__(self):
        return "Name: " + self.name + "," + \
               "Description: " + self.description


""" Lesson model """
class Lesson(models.Model):
    """ Represents a lesson """
    title = models.CharField(max_length=200, default="title")
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField()


""" Emrpllment model """
class Enrollment(models.Model):
    """ Represents enrollment of a student in a course """
    AUDIT = 'audit'
    HONOR = 'honor'
    BETA = 'BETA'
    COURSE_MODES = [
        (AUDIT, 'Audit'),
        (HONOR, 'Honor'),
        (BETA, 'BETA')
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_enrolled = models.DateField(default=now)
    mode = models.CharField(max_length=5, choices=COURSE_MODES, default=AUDIT)
    rating = models.FloatField(default=5.0)


""" Question model """
class Question(models.Model):
    """ Represents a question in an exam / assessment"""
    question_text = models.CharField(max_length=300)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    question_grade = models.FloatField(default=50.0)

    def is_get_score(self, selected_ids):
        all_answers = self.choice_set.filter(is_correct=True).count()
        selected_correct = self.choice_set.filter(is_correct=True, id__in=selected_ids).count()
        if all_answers == selected_correct:
            return True
        else:
            return False

    def __str__(self):
        return self.question_text


""" Choice model """
class Choice(models.Model):
    """ Represents a choice among as anwer to a question """
    choice_content = models.CharField(max_length=300)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_content


""" Submission model """
class Submission(models.Model):
    """ Represents a submission of selected choices """
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE)
    choices = models.ManyToManyField(Choice)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Submission for {self.course.name} by {self.enrollment.user.username}"

onlinecourse/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Course, Enrollment, Submission, Choice, Question
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout, authenticate
import logging
# Get an instance of a logger
logger = logging.getLogger(__name__)


""" Registration view """
def registration_request(request):
    """ Represents a user registration operation """
    context = {}
    if request.method == 'GET':
        return render(request, 'onlinecourse/user_registration_bootstrap.html', context)
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        
        # check if user exists
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
            
        #check if user doesn't already exist,create a new user
        if not user_exist:
            user = User.objects.create_user(username=username, 
                                            first_name=first_name, 
                                            last_name=last_name, 
                                            password=password
                                            )
            login(request, user)
            return redirect("onlinecourse:index")
        else: # if user exists
            context['message'] = "User already exists."
            return render(request, 'onlinecourse/user_registration_bootstrap.html', context)

""" Login view """
def login_request(request):
    """ Represents a login operation """
    context = {}
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('onlinecourse:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'onlinecourse/user_login_bootstrap.html', context)
    else:
        return render(request, 'onlinecourse/user_login_bootstrap.html', context)


""" Logout """
def logout_request(request):
""" Represents a logout operation """
    logout(request)
    return redirect('onlinecourse:index')


def check_if_enrolled(user, course):
    is_enrolled = False
    if user.id is not None:
        # Check if user enrolled
        num_results = Enrollment.objects.filter(user=user, course=course).count()
        if num_results > 0:
            is_enrolled = True
    return is_enrolled


""" Course List View """
class CourseListView(generic.ListView):
    """ Lists all available courses"""
    template_name = 'onlinecourse/course_list_bootstrap.html'
    context_object_name = 'course_list'

    def get_queryset(self):
        user = self.request.user
        courses = Course.objects.order_by('-total_enrollment')[:10]
        for course in courses:
            if user.is_authenticated:
                course.is_enrolled = check_if_enrolled(user, course)
        return courses


"""Course Details View """
class CourseDetailView(generic.DetailView):
    """ Displays details of a particular course """
    model = Course
    template_name = 'onlinecourse/course_detail_bootstrap.html'


""" Enrollment view """
def enroll(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    user = request.user

    is_enrolled = check_if_enrolled(user, course)
    if not is_enrolled and user.is_authenticated:
        # Create an enrollment
        Enrollment.objects.create(user=user, course=course, mode='honor')
        course.total_enrollment += 1
        course.save()

    return HttpResponseRedirect(reverse(viewname='onlinecourse:course_details', args=(course.id,)))


""" Submit choices view """
def submit(request, course_id):
    # Get the courses by id
    course = get_object_or_404(Course, pk=course_id)
    # Get the user
    user = request.user
    # Filter the enrollment by user and course
    enrollment = Enrollment.objects.filter(user=user, course=course).get()
    # Create a submission id
    submission = Submission.objects.create(enrollment_id=enrollment.id)

    choices = extract_answers(request)
    for a in choices:
        temp_c = Choice.objects.filter(id=int(a)).get()
        submission.choices.add(temp_c)

    submission.save()
    return HttpResponseRedirect(reverse(viewname='onlinecourse:show_exam_result', args=(course.id, submission.id)))


def extract_answers(request):
    submitted_choices = []
    for key in request.POST:
        if key.startswith('choice'):
            value = request.POST[key]
            choice_id = int(value)
            submitted_choices.append(choice_id)
    return submitted_choices


""" Exam results view """
def show_exam_result(request, course_id, submission_id):
    # Get course and submission based on ids
    course = get_object_or_404(Course, pk=course_id)
    submission = get_object_or_404(Submission, pk=submission_id)

    # Get the selected choice ids from the submission record
    choices = submission.choices.all()
    questions = course.question_set.all()

    # Calculate total score
    total = sum([q.question_grade for q in questions])
    achieved_score = 0

    # Get the list selected choices
    selected_choice_ids = choices.values_list("id", flat=True)

    for question in questions:
        if question.is_get_score(choices):
            achieved_score += question.question_grade

    grade = round(achieved_score/total*100)

    context = {'course': course,
               'submission': submission,
               'grade': grade,
               'total': total,
               'choices': choices,
               'selected_choice_ids': selected_choice_ids
               }

    return render(request, 'onlinecourse/exam_result_bootstrap.html', context)

onlinecourse/templates/onlinecourse/base.html
<!DOCTYPE html>
    {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Courses</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <!-- Navigation bar -->
    {% block nav %}
      <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                  <a class="navbar-brand" href="#">Online Course</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% endblock nav %}

    {% block content %} {% endblock content %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

onlinecourse/templates/onlinecourse/course_detail_bootstrap.html
{% extends 'onlinecourse/base.html' %}

{% block nav %}
{% include 'onlinecourse/base.html' %}
{% endblock nav %}

{% block content %}
<!-- Page content -->
<div class="container my-5">
    <h2>{{ course.name }}</h2>
    <div class="card-columns-vertical">
        <!-- Display all lessons in course-->
        {% for lesson in course.lesson_set.all %}
        <div class="card mt-1">
            <div class="card-header"><h5>Lesson: {{lesson.title}}</h5></div>
            <div class="card-body">{{lesson.content}}</div>
        </div>
        {% endfor %}
    </div>

    {% if user.is_authenticated %}
    <div id="exam" class="row mt-5">
        <div class="col">
            <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">Show Exam</button>
            <div id="demo" class="collapse">
                <!-- A choice submission form -->
                <form id="questionform" action="{% url 'onlinecourse:submit' course.id %}" method="post">
                    <!-- for each question in the course, display question ...-->
                    {% for question in course.question_set.all %}
                    <div class="card mt-1">
                        <div class="card-header"><h5>{{ question.question_text}}</h5></div>
                        {% csrf_token %}
                        <div class="form-group">
                            <!-- for each choice/answer in the question, display choice/answer ...-->
                            {% for choice in question.choice_set.all %}
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input type="checkbox" name="choice_{{choice.id}}"
                                           class="form-check-input" id="{{choice.id}}"
                                           value="{{choice.id}}">{{ choice.choice_content }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    <input class="btn btn-success mt-2" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
    {% else %}
    <p class="text-danger">Please
        <a href="{% url 'onlinecourse:login' %}" class="btn btn-link">Login</a>
        to access exam!
    </p>
    {% endif %}
</div>
{% endblock content %}

onlinecourse/templates/onlinecourse/course_list_bootstrap.html
{% extends 'onlinecourse/base.html' %}

{% block nav %}
{% include 'onlinecourse/base.html' %}
{% endblock nav %}

{% block content %}
<!-- Page content -->
{% if course_list %}
<div class="container">
    <div class="card-deck justify-content-center my-5">
        <!-- List of available courses -->
        {% for course in course_list %}
            <div class="card" style="max-width: 18rem;">
                <img class="card-img p-3" src="{{MEDIA_URL}}/{{ course.image }}" width="240px" height="240px"
                     alt="Course image">
                <div class="card-body bg-light">
                    <a href="{% url 'onlinecourse:course_details' course.id %}"
                       class="card-title">
                        {{ course.name }}
                    </a>-
                    <span class="text-success">{{ course.total_enrollment}} enrolled</span>
                    <p class="card-text">{{ course.description}}</p>
                    <form action="{% url 'onlinecourse:enroll' course.id %}" method="post">
                        {% csrf_token %}

                        {% if user.is_authenticated %}
                            <input class="btn btn-primary" type="submit"
                               value="{% if course.is_enrolled %} Enter {% else %} Enroll {% endif %}">
                        {% else %}
                            <p>Please login to enroll or resume courses!</p>
                            <a href="{% url 'onlinecourse:login' %}" class="btn btn-primary">Login</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% else %}
<!-- Display this if no courses are available -->
<p>No courses are available.</p>
{% endif %}

{% endblock content %}

onlinecourse/templates/onlinecourse/exam_result_bootstrap.html
{% extends 'onlinecourse/base.html' %}

{% block nav %}
{% include 'onlinecourse/base.html' %}
{% endblock nav %}

{% block content %}

<div class="container-fluid">

    <div>
        <h1>Exam Result</h1>
        <h2>Course: {{ course.name }}</h2>
        <!-- <h3>Submission ID: {{ submission.id }}</h3> -->
    </div>

    {% if grade > 80 %}
    <div class="alert alert-success">
        <b>Congratulations, {{ submission.enrollment.user.username }}!</b>
        You have passed the exam and completed the course with {{ grade }}%
    </div>
    {% else %}
    <div class="alert alert-danger">
        <b>Failed.</b> Sorry, {{ submission.enrollment.user.username }}! You have failed the exam with {{ grade }}%
    </div>
    <a class="btn btn-link text-danger" href="{% url 'onlinecourse:course_details' course.id %}">Retake Test</a>
    {% endif %}

    <div class="card-deck my-5">
        {% for question in course.question_set.all %}
        <div class="card">
            <div class="table-responsive">
             <table class='table table-striped' style='width:500; margin: '>
                <tr>
                    <th colspan="2">{{ question.question_text }} ({{ question.question_grade }} points)</th>
                </tr>
                {% for choice in question.choice_set.all %}
                <tr>
                    <td>{{ choice.choice_content }}</td>
                    <td style='background-color:
                    {% if choice.is_correct %}
                    palegreen
                    {% elif choice.id in selected_choice_ids %}
                    lightblue
                    {% else %}
                    lightpink
                    {% endif %}'>
                        Right choice: <b>{{ choice.is_correct }}</b>
                        <br>
                        Your choice: <b>
                        {% if choice.id in selected_choice_ids %}
                        selected
                        {% else %}
                        No
                        {% endif %}
                    </b>
                    </td>
                </tr>
                {% endfor %}
            </table>
            </div>
            <br>
        </div>
    {% endfor %}
    </div>

</div>

{% endblock content %}

onlinecourse/templates/onlinecourse/user_login_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Login form -->
    <form action="{% url 'onlinecourse:login' %}" method="post">
        {% csrf_token %}
        <div class="container"> <!--Style root div with .container class -->
            <h1>Login</h1>
            <div class="form-group"> <!--Style second div with .form-group class -->
              <label for="username"><b>User Name</b></label>
              <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
              <label for="psw"><b>Password</b></label>
              <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            </div>
            {% if message %}
              <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
              </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </form>

</body>

onlinecourse/templates/onlinecourse/user_registration_bootstrap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <!-- Navigation bar -->
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'onlinecourse:index' %}">Home</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                    <a class="btn btn-link" href="#">{{ user.first_name }}({{ user.username }})</a>
                    <a class="btn btn-link" href="{% url 'onlinecourse:logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <form class="form-inline" action="{% url 'onlinecourse:login' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Username" name="username" >
                            <input type="password" class="form-control" placeholder="Username" name="psw" >
                            <button class="btn btn-primary" type="submit">Login</button>
                            <a class="btn btn-link" href="{% url 'onlinecourse:registration' %}">Sign Up</a>
                        </div>
                    </form>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- Stylize Registration form -->
    <form action="{% url 'onlinecourse:registration' %}" method="post">
        <div class="container"> <!--Style root div with .container class -->
            {% csrf_token %}
            <h1>Sign Up</h1>
            <hr>
            <div class="form-group"> <!--Style second div with .form-group class -->
                <label for="username"><b>User Name</b></label>
                <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
                <label for="firstname"><b>First Name</b></label>
                <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
                <label for="psw"><b>Password</b></label>
                <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
                {% if message %}
                <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                    {{ message }}
                </div>
                {% endif %}
                <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
            </div>
        </div>
    </form>

</body>